---
# tasks file for Jenkins

  tasks:
  - name: Installing boto & boto3 on local system
    pip:
      name: "{{ item }}"
      state: present
    loop: 
    - boto
    - boto3

  - name: Creating Security Group for jenkins while Launching EC2 Instance
    amazon.aws.ec2_group:
      name: "{{ security_group }}"
      description: Security Group for allowing port for SSH & HTTP Protocol
      region: "ap-south-1"
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: all
        from_port: 8080
        to_port: 8080
        cidr_ip: "{{ cidr_ip }}" 
      rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
    vars:
      ansible_python_interpreter: /bin/python3

  - name: Launching EC2 Instance
    amazon.aws.ec2_instance:
      region: "ap-south-1"
      image_id: "{{ image_id }}" 
      instance_type: "t2.micro"
      vpc_subnet_id: "subnet-0549bad06abbc5d27"
      security_group: "{{ security_group }}"
      key_name: "{{ key_name }}"
      name: "Jenkins"      
      state: started
      wait: yes
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
    vars:
      ansible_python_interpreter: /bin/python3
    register: ec2

  - name: Add new launched instance to host group to Install Docker
    add_host:
      name: "{{ item.public_ip_address }}"
      group: "Jenkins"
    loop: "{{ ec2.instances }}"

  - name: Staring SSH Protocol for Connectivity with EC2 Instance
    wait_for:
      host: "{{ item.public_dns_name }}"
      port: 22
      state: started
    loop: "{{ ec2.instances }}"

- hosts: Jenkins
  tasks:
  - name: Upgrade all packages
    yum:
      name: '*'
      state: latest
 
  - name: "Download Yum Repository for Jenkins"
    get_url: 
      dest: /etc/yum.repos.d/jenkins.repo
      url: "https://pkg.jenkins.io/redhat-stable/jenkins.repo"

  - name: "Import a key file from Jenkins-CI to enable installation from the package"
    shell: "rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key"

  - name: "Uprgading Yum"
    shell: "yum upgrade -y"

  - name: "Install Java"
    shell: "amazon-linux-extras install java-openjdk11 -y"

  - name: Installing Jenkins & Git (For Github Repo Integration)
    package:
      name: "{{ item }}"
      state: present
    loop:
      - git
      - jenkins  

  - name: Staring & enabling Jenkins Service
    service:
      name: "jenkins"
      state: started
      enabled: yes

  - name: "Store the Password in a variable for Jenkins Login"
    shell: "cat /var/lib/jenkins/secrets/initialAdminPassword" 
    register: password

  - name: Debug the variable 
    debug:
      var: password


 
 


      
