apiVersion: v1
kind: Service
metadata:
  name: webcontainer
  labels:
    app: webcontainer

spec:
  type: NodePort
  selector:
    app: webcontainer
  ports:
  - targetPort: 80
    port: 80
    nodePort: 30038



